name: Test

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            python-version:
              - "3.9"
              - "3.10"
              - "3.11"
              - "3.12"
              - "3.13"
              - "3.14"

    env:
      UV_PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: "actions/checkout@v6"
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - run: uv sync --locked --all-extras --dev

    - name: Lint with ruff
      run: uv run ruff check

    - name: Format with ruff
      run: uv run ruff format --check --diff

    - name: Typecheck
      run: uv run mypy

    - name: Run tests
      run: uv run pytest

    - name: Upload htmldoc
      uses: actions/upload-artifact@v4
      with:
        name: htmlcov
        path: htmlcov

    - name: Build docs
      run: |
        cd doc
        uv run make html

    - name: Upload doc
      uses: actions/upload-artifact@v4
      with:
        name: doc
        path: doc/_build/html
